<?php
/**
 * Main constants.
 */

define( 'COPY_PASTE_ORDER_FOR_WOOCOMMERCE_PLUGIN_VERSION', '1.0.0' );
define( 'COPY_PASTE_ORDER_FOR_WOOCOMMERCE_DATABASE_VERSION', '10' );

define( 'COPY_PASTE_ORDER_FOR_WOOCOMMERCE_PLUGIN_PATH', plugin_dir_path( __DIR__ ) );
define( 'COPY_PASTE_ORDER_FOR_WOOCOMMERCE_PLUGIN_BASENAME', plugin_basename( __DIR__ ) );
define( 'COPY_PASTE_ORDER_FOR_WOOCOMMERCE_PLUGIN_URL', trailingslashit( plugin_dir_url( __DIR__ ) ) );

define( 'COPY_PASTE_ORDER_FOR_WOOCOMMERCE_PLUGIN_OPTIONS_KEY', 'cpofw_' );

define( 'COPY_PASTE_ORDER_FOR_WOOCOMMERCE_ORDER_JSON_VERSION', '1.0.0' );
